package com.sinosoft.ap.system.log.domain;

import java.util.Date;

public class ApsUserVisiteSystemLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aps_user_visite_system_log.log_id
     *
     * @mbggenerated Wed Aug 01 22:47:22 CST 2018
     */
    private String logId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aps_user_visite_system_log.user_id
     *
     * @mbggenerated Wed Aug 01 22:47:22 CST 2018
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aps_user_visite_system_log.user_name
     *
     * @mbggenerated Wed Aug 01 22:47:22 CST 2018
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aps_user_visite_system_log.organ_code
     *
     * @mbggenerated Wed Aug 01 22:47:22 CST 2018
     */
    private String organCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aps_user_visite_system_log.system_code
     *
     * @mbggenerated Wed Aug 01 22:47:22 CST 2018
     */
    private String systemCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aps_user_visite_system_log.system_name
     *
     * @mbggenerated Wed Aug 01 22:47:22 CST 2018
     */
    private String systemName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aps_user_visite_system_log.visite_time
     *
     * @mbggenerated Wed Aug 01 22:47:22 CST 2018
     */
    private Date visiteTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aps_user_visite_system_log.organ_name
     *
     * @mbggenerated Wed Aug 01 22:47:22 CST 2018
     */
    private String organName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aps_user_visite_system_log.parent_organ_id
     *
     * @mbggenerated Wed Aug 01 22:47:22 CST 2018
     */
    private String parentOrganId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aps_user_visite_system_log.system_type
     *
     * @mbggenerated Wed Aug 01 22:47:22 CST 2018
     */
    private Integer systemType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aps_user_visite_system_log.log_id
     *
     * @return the value of aps_user_visite_system_log.log_id
     *
     * @mbggenerated Wed Aug 01 22:47:22 CST 2018
     */
    public String getLogId() {
        return logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aps_user_visite_system_log.log_id
     *
     * @param logId the value for aps_user_visite_system_log.log_id
     *
     * @mbggenerated Wed Aug 01 22:47:22 CST 2018
     */
    public void setLogId(String logId) {
        this.logId = logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aps_user_visite_system_log.user_id
     *
     * @return the value of aps_user_visite_system_log.user_id
     *
     * @mbggenerated Wed Aug 01 22:47:22 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aps_user_visite_system_log.user_id
     *
     * @param userId the value for aps_user_visite_system_log.user_id
     *
     * @mbggenerated Wed Aug 01 22:47:22 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aps_user_visite_system_log.user_name
     *
     * @return the value of aps_user_visite_system_log.user_name
     *
     * @mbggenerated Wed Aug 01 22:47:22 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aps_user_visite_system_log.user_name
     *
     * @param userName the value for aps_user_visite_system_log.user_name
     *
     * @mbggenerated Wed Aug 01 22:47:22 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aps_user_visite_system_log.organ_code
     *
     * @return the value of aps_user_visite_system_log.organ_code
     *
     * @mbggenerated Wed Aug 01 22:47:22 CST 2018
     */
    public String getOrganCode() {
        return organCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aps_user_visite_system_log.organ_code
     *
     * @param organCode the value for aps_user_visite_system_log.organ_code
     *
     * @mbggenerated Wed Aug 01 22:47:22 CST 2018
     */
    public void setOrganCode(String organCode) {
        this.organCode = organCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aps_user_visite_system_log.system_code
     *
     * @return the value of aps_user_visite_system_log.system_code
     *
     * @mbggenerated Wed Aug 01 22:47:22 CST 2018
     */
    public String getSystemCode() {
        return systemCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aps_user_visite_system_log.system_code
     *
     * @param systemCode the value for aps_user_visite_system_log.system_code
     *
     * @mbggenerated Wed Aug 01 22:47:22 CST 2018
     */
    public void setSystemCode(String systemCode) {
        this.systemCode = systemCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aps_user_visite_system_log.system_name
     *
     * @return the value of aps_user_visite_system_log.system_name
     *
     * @mbggenerated Wed Aug 01 22:47:22 CST 2018
     */
    public String getSystemName() {
        return systemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aps_user_visite_system_log.system_name
     *
     * @param systemName the value for aps_user_visite_system_log.system_name
     *
     * @mbggenerated Wed Aug 01 22:47:22 CST 2018
     */
    public void setSystemName(String systemName) {
        this.systemName = systemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aps_user_visite_system_log.visite_time
     *
     * @return the value of aps_user_visite_system_log.visite_time
     *
     * @mbggenerated Wed Aug 01 22:47:22 CST 2018
     */
    public Date getVisiteTime() {
        return visiteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aps_user_visite_system_log.visite_time
     *
     * @param visiteTime the value for aps_user_visite_system_log.visite_time
     *
     * @mbggenerated Wed Aug 01 22:47:22 CST 2018
     */
    public void setVisiteTime(Date visiteTime) {
        this.visiteTime = visiteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aps_user_visite_system_log.organ_name
     *
     * @return the value of aps_user_visite_system_log.organ_name
     *
     * @mbggenerated Wed Aug 01 22:47:22 CST 2018
     */
    public String getOrganName() {
        return organName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aps_user_visite_system_log.organ_name
     *
     * @param organName the value for aps_user_visite_system_log.organ_name
     *
     * @mbggenerated Wed Aug 01 22:47:22 CST 2018
     */
    public void setOrganName(String organName) {
        this.organName = organName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aps_user_visite_system_log.parent_organ_id
     *
     * @return the value of aps_user_visite_system_log.parent_organ_id
     *
     * @mbggenerated Wed Aug 01 22:47:22 CST 2018
     */
    public String getParentOrganId() {
        return parentOrganId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aps_user_visite_system_log.parent_organ_id
     *
     * @param parentOrganId the value for aps_user_visite_system_log.parent_organ_id
     *
     * @mbggenerated Wed Aug 01 22:47:22 CST 2018
     */
    public void setParentOrganId(String parentOrganId) {
        this.parentOrganId = parentOrganId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aps_user_visite_system_log.system_type
     *
     * @return the value of aps_user_visite_system_log.system_type
     *
     * @mbggenerated Wed Aug 01 22:47:22 CST 2018
     */
    public Integer getSystemType() {
        return systemType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aps_user_visite_system_log.system_type
     *
     * @param systemType the value for aps_user_visite_system_log.system_type
     *
     * @mbggenerated Wed Aug 01 22:47:22 CST 2018
     */
    public void setSystemType(Integer systemType) {
        this.systemType = systemType;
    }
}