package com.sinosoft.ap.system.log.domain;

import com.sinosoft.ap.system.log.domain.ApsUserVisiteSystemLog;
import com.sinosoft.ap.system.log.domain.ApsUserVisiteSystemLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ApsUserVisiteSystemLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aps_user_visite_system_log
     *
     * @mbggenerated Wed Aug 01 22:47:22 CST 2018
     */
    int countByExample(ApsUserVisiteSystemLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aps_user_visite_system_log
     *
     * @mbggenerated Wed Aug 01 22:47:22 CST 2018
     */
    int deleteByExample(ApsUserVisiteSystemLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aps_user_visite_system_log
     *
     * @mbggenerated Wed Aug 01 22:47:22 CST 2018
     */
    int deleteByPrimaryKey(String logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aps_user_visite_system_log
     *
     * @mbggenerated Wed Aug 01 22:47:22 CST 2018
     */
    int insert(ApsUserVisiteSystemLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aps_user_visite_system_log
     *
     * @mbggenerated Wed Aug 01 22:47:22 CST 2018
     */
    int insertSelective(ApsUserVisiteSystemLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aps_user_visite_system_log
     *
     * @mbggenerated Wed Aug 01 22:47:22 CST 2018
     */
    List<ApsUserVisiteSystemLog> selectByExample(ApsUserVisiteSystemLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aps_user_visite_system_log
     *
     * @mbggenerated Wed Aug 01 22:47:22 CST 2018
     */
    ApsUserVisiteSystemLog selectByPrimaryKey(String logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aps_user_visite_system_log
     *
     * @mbggenerated Wed Aug 01 22:47:22 CST 2018
     */
    int updateByExampleSelective(@Param("record") ApsUserVisiteSystemLog record, @Param("example") ApsUserVisiteSystemLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aps_user_visite_system_log
     *
     * @mbggenerated Wed Aug 01 22:47:22 CST 2018
     */
    int updateByExample(@Param("record") ApsUserVisiteSystemLog record, @Param("example") ApsUserVisiteSystemLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aps_user_visite_system_log
     *
     * @mbggenerated Wed Aug 01 22:47:22 CST 2018
     */
    int updateByPrimaryKeySelective(ApsUserVisiteSystemLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aps_user_visite_system_log
     *
     * @mbggenerated Wed Aug 01 22:47:22 CST 2018
     */
    int updateByPrimaryKey(ApsUserVisiteSystemLog record);
    
    ApsUserVisiteSystemLog selectUserInfosByUserId(String userId);
}